# Generated by Django 3.2.12 on 2022-04-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='file',
            field=models.IntegerField(),
        ),
    ]
